# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: "Home"
    url: "/"
    weight: 10
  - name: "Calendar"
    url: "/calendar/"
    weight: 20
  - name: "Registration"
    url: "/registration/"
    weight: 30
  - name: "People"
    url: "/people/"
    weight: 40
  - name: "Instructors Area"
    url: "/instructors/"
    weight: 50
  - name: "Contact"
    url: "/contact/"
    weight: 60
  - name: "About"
    url: "/about/"
    weight: 70
